// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/parallelGroupBy.h"
#include <Rcpp.h>

using namespace Rcpp;

// make_index_impl1_serial
List make_index_impl1_serial(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_impl1_serial(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_impl1_serial(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index_parallel
List make_index_parallel(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_parallel(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_parallel(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index_concurrent_hash_map
List make_index_concurrent_hash_map(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_concurrent_hash_map(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_concurrent_hash_map(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index_threads_unorderedmap_joinConcurrentMap
List make_index_threads_unorderedmap_joinConcurrentMap(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_threads_unorderedmap_joinConcurrentMap(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_threads_unorderedmap_joinConcurrentMap(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
