// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_index_serial
List make_index_serial(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_serial(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_serial(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index_parallel
List make_index_parallel(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_parallel(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_parallel(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index_concurrent_hash_map
List make_index_concurrent_hash_map(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index_concurrent_hash_map(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index_concurrent_hash_map(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index3
List make_index3(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index3(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index3(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index4
List make_index4(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index4(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index4(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index5
List make_index5(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index5(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index5(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index6
List make_index6(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index6(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index6(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// make_index7
List make_index7(DataFrame data, CharacterVector by);
RcppExport SEXP parallelGroupBy_make_index7(SEXP dataSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type by(bySEXP );
        List __result = make_index7(data, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
