# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_index_impl1_serial <- function(data, by) {
    .Call('parallelGroupBy_make_index_impl1_serial', PACKAGE = 'parallelGroupBy', data, by)
}

make_index_parallel <- function(data, by) {
    .Call('parallelGroupBy_make_index_parallel', PACKAGE = 'parallelGroupBy', data, by)
}

make_index_concurrent_hash_map <- function(data, by) {
    .Call('parallelGroupBy_make_index_concurrent_hash_map', PACKAGE = 'parallelGroupBy', data, by)
}

make_index_threads_unorderedmap_joinConcurrentMap <- function(data, by) {
    .Call('parallelGroupBy_make_index_threads_unorderedmap_joinConcurrentMap', PACKAGE = 'parallelGroupBy', data, by)
}

